# Generated by Django 5.1.6 on 2025-02-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0003_alter_denuncia_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='imagen',
            field=models.ImageField(upload_to='denuncias-imgs', verbose_name='Imagen'),
        ),
    ]
