# Generated by Django 5.1.6 on 2025-02-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0005_alter_denuncia_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='denuncia',
            options={},
        ),
    ]
